rss_feeds:
  - "https://www.rmf24.pl/fakty/polska/feed"
  - "https://rss.onet.pl/"
  - "https://gazeta.pl/rss/"
  - "https://www.ceskatelevize.cz/rss/ct24.xml"
  - "https://www.idnes.cz/rss.aspx"
  - "https://rss.aktualne.cz/"
  - "https://www.sme.sk/rss/"
  - "https://spravy.pravda.sk/rss/"
  - "https://www.aktuality.sk/rss/"
  - "https://meduza.io/rss/all"
  - "https://rss.ria.ru/export/rss2/world/index.xml"
  - "https://www.themoscowtimes.com/rss"
  - "https://www.pravda.com.ua/rss"
  - "https://kyivindependent.com/feed"
  - "https://www.kyivpost.com/rss/site.xml"
  - "https://www.radiosvoboda.org/api/feeds"
  - "https://nashaniva.com/ru/rss/"
  - "https://www.rferl.org/api/feeds?region=Belarus"
  - "https://www.rts.rs/rss/ci.xml"
  - "https://www.blic.rs/rss"
  - "https://www.danas.rs/feed/"
  - "https://www.hrt.hr/feeds/"
  - "https://www.index.hr/rss/"
  - "https://www.jutarnji.hr/rss"
  - "https://balkaninsight.com/feed/"
  - "https://cin.ba/feed/"
  - "https://ba.n1info.com/rss/"
  - "https://www.vijesti.me/rss"
  - "https://www.raskrinkavanje.me/rss"
  - "https://kallxo.com/feed/"
  - "https://www.koha.net/rss"
  - "https://meta.mk/feed/"
  - "https://www.slobodenpecat.mk/feed/"
  - "https://btvnovinite.bg/rss"
  - "https://nova.bg/news/rss"
  - "https://www.dnevnik.bg/rss.php"
  - "https://www.rtvslo.si/rss/"
  - "https://www.delo.si/rss/"
  - "https://podcrto.si/feed/"
  - "https://www.pb.pl/rss"
  - "https://hn.ihned.cz/rss"
  - "https://www.hnonline.sk/rss"
  - "https://www.vedomosti.ru/rss/news.xml"
  - "https://www.interfax.com.ua/ua/rss/business/"
  - "https://bizlife.rs/feed/"
  - "https://www.poslovni.hr/rss"
  - "https://cin.ba/feed/"
  - "https://www.vijesti.me/rss/business"
  - "https://biznes.koha.net/rss"
  - "https://meta.mk/feed/"
  - "https://www.capital.bg/rss"
  - "https://www.monitor.si/rss/"
  - "https://www.imf.org/external/index.xml"

lt_endpoints:
  - "https://libretranslate.com/translate"
  - "https://translate.astian.org/translate"
  - "https://libretranslate.de/translate"
  - "https://translate.argosopentech.com/translate"

discord_webhook: "https://discordapp.com/api/webhooks/1392262052742959155/DEQ5zlgo3bdqzFkrLX1OyxyvybmRLnVNqcAQjeDVwt8FtUeXhCodvR6UuUILBdAUGvQi"


  
slavic_countries:
  # Polska
  - polska
  - poland
  - pl
  - warszawa
  - warsaw
  - kraków
  - krakow
  - wrocław
  - wroclaw
  - gdańsk
  - gdansk
  - poznan
  - łódź
  - lodz
  - szczecin
  - katowice
  - lubin
  # Czechy
  - czechy
  - czech republic
  - cz
  - praga
  - prague
  - brno
  - ostrava
  # Słowacja
  - słowacja
  - slovakia
  - sk
  - bratysława
  - bratislava
  - koszyce
  - presov
  # Ukraina
  - ukraina
  - ukraine
  - ua
  - kijów
  - kyiv
  - lwów
  - lviv
  - odesa
  - charków
  - kharkiv
  # Rosja
  - rosja
  - russia
  - ru
  - moskwa
  - moscow
  - petersburg
  - saint petersburg
  # Białoruś
  - białoruś
  - belarus
  - by
  - mińsk
  - minsk
  # Serbia
  - serbia
  - rs
  - belgrad
  - belgrade
  - novi sad
  # Chorwacja
  - chorwacja
  - croatia
  - hr
  - zagrzeb
  - zagreb
  - split
  - rijeka
  # Słowenia
  - słowenia
  - slovenia
  - si
  - lubiana
  - ljubljana
  # Bośnia i Hercegowina
  - bośnia
  - bosnia
  - ba
  - sarajewo
  - sarajevo
  - banja luka
  # Czarnogóra
  - czarnogóra
  - montenegro
  - me
  - podgorica
  # Macedonia Północna
  - macedonia
  - north macedonia
  - mk
  - skopje
  # Kosowo
  - kosowo
  - kosovo
  - xk
  - prisztina
  - pristina
  # Bułgaria
  - bułgaria
  - bulgaria
  - bg
  - sofia
