name: RSS Fetch & Translate

on:
  schedule:
    - cron: '*/15 * * * *'  # co 15 minut
  workflow_dispatch:        # opcjonalnie: uruchom ręcznie

jobs:
  run-news-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python rss_reader.py
